makefile xDD

protoc -I proto/auth --go_out=./gen/go/auth --go_opt=paths=source_relative --go-grpc_out=./gen/go/auth --go-grpc_opt=paths=source_relative ./proto/auth/auth.proto
protoc -I proto/calc --go_out=./gen/go/calc --go_opt=paths=source_relative --go-grpc_out=./gen/go/calc --go-grpc_opt=paths=source_relative ./proto/calc/calc.proto
protoc -I proto/agent --go_out=./gen/go/agent --go_opt=paths=source_relative --go-grpc_out=./gen/go/agent --go-grpc_opt=paths=source_relative ./proto/agent/agent.proto

go run ./app/cmd/migrator --storage-path=./app/storage/app.db --migrations-path=./app/migrations

go run ./app/cmd/server/auth  --config=./app/config/local.yaml
go run ./app/cmd/server/orkestrator  --config=./app/config/local.yaml
go run ./app/cmd/server/agent  --config=./app/config/local.yaml
go run ./app/cmd/client/goClients