protoc proto/auth/auth.proto -I proto/auth/auth.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative



go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./migrations